---
version: '3.7'

services:
  email-writer-1:
   image: fdimage:latest
   networks:
     - kafka-network
   command:
     "bash -c '
          java -cp /app/friendsdrinks-0.0.1.jar andrewgrant.friendsdrinks.email.WriterService /app/dev.properties
          '"

  email-writer-2:
    image: fdimage:latest
    networks:
      - kafka-network
    command:
      "bash -c '
          java -cp /app/friendsdrinks-0.0.1.jar andrewgrant.friendsdrinks.email.WriterService /app/dev.properties
          '"

  email-validation-service-1:
    image: fdimage:latest
    networks:
      - kafka-network
    command:
      "bash -c '
          java -cp /app/friendsdrinks-0.0.1.jar andrewgrant.friendsdrinks.email.ValidationService /app/dev.properties
          '"

  email-validation-service-2:
    image: fdimage:latest
    networks:
      - kafka-network
    command:
      "bash -c '
          java -cp /app/friendsdrinks-0.0.1.jar andrewgrant.friendsdrinks.email.ValidationService /app/dev.properties
          '"

  fraud-validation-service-1:
    image: fdimage:latest
    networks:
      - kafka-network
    command:
      "bash -c '
          java -cp /app/friendsdrinks-0.0.1.jar andrewgrant.friendsdrinks.fraud.ValidationService /app/dev.properties
          '"

  fraud-validation-service-2:
    image: fdimage:latest
    networks:
      - kafka-network
    command:
      "bash -c '
          java -cp /app/friendsdrinks-0.0.1.jar andrewgrant.friendsdrinks.fraud.ValidationService /app/dev.properties
          '"


  user-validation-service-1:
    image: fdimage:latest
    networks:
      - kafka-network
    command:
      "bash -c '
          java -cp /app/friendsdrinks-0.0.1.jar andrewgrant.friendsdrinks.user.ValidationService /app/dev.properties
          '"

  user-validation-service-2:
    image: fdimage:latest
    networks:
      - kafka-network
    command:
      "bash -c '
          java -cp /app/friendsdrinks-0.0.1.jar andrewgrant.friendsdrinks.user.ValidationService /app/dev.properties
          '"

  user-validation-aggregator-service-1:
    image: fdimage:latest
    networks:
      - kafka-network
    command:
      "bash -c '
          java -cp /app/friendsdrinks-0.0.1.jar andrewgrant.friendsdrinks.user.ValidationAggregatorService /app/dev.properties
          '"

  user-validation-aggregator-service-2:
    image: fdimage:latest
    networks:
      - kafka-network
    command:
      "bash -c '
          java -cp /app/friendsdrinks-0.0.1.jar andrewgrant.friendsdrinks.user.ValidationAggregatorService /app/dev.properties
          '"

  front-end-api:
    image: fdimage:latest
    networks:
      - kafka-network
    ports:
      - "8080"
    command:
      "bash -c 'sleep 15 && \
          java -cp /app/friendsdrinks-0.0.1.jar andrewgrant.friendsdrinks.frontend.api.Service /app/dev.properties 8080
          '"

networks:
  kafka-network:
    external: true
    name: friendsdrinks_default
