---
version: '3.7'

services:
  friendsdrinks-request-service:
    image: andyg001/friendsdrinksbackend:latest
    networks:
      - kafka-network
    volumes:
      - ./dockercompose:/app/config
    command:
      "bash -c '
          java -DlogPath=/app/ -cp /app/friendsdrinks-0.0.1.jar andrewgrant.friendsdrinks.RequestService /app/config/dev.properties \
          -DlogPath=/app/
          '"

  friendsdrinks-membership-request-service:
    image: andyg001/friendsdrinksbackend:latest
    networks:
      - kafka-network
    volumes:
      - ./dockercompose:/app/config
    command:
      "bash -c '
          java -DlogPath=/app/ -cp /app/friendsdrinks-0.0.1.jar andrewgrant.friendsdrinks.membership.RequestService /app/config/dev.properties \
          -DlogPath=/app/
          '"

  friendsdrinks-membership-writer-service:
    image: andyg001/friendsdrinksbackend:latest
    networks:
      - kafka-network
    volumes:
      - ./dockercompose:/app/config
    command:
      "bash -c '
          java -DlogPath=/app/ -cp /app/friendsdrinks-0.0.1.jar andrewgrant.friendsdrinks.membership.MembershipWriterService /app/config/dev.properties \
          -DlogPath=/app/
          '"

  friendsdrinks-meetup-writer-service:
    image: andyg001/friendsdrinksbackend:latest
    networks:
      - kafka-network
    volumes:
      - ./dockercompose:/app/config
    command:
      "bash -c '
          java -DlogPath=/app/ -cp /app/friendsdrinks-0.0.1.jar andrewgrant.friendsdrinks.meetup.WriterService /app/config/dev.properties \
          -DlogPath=/app/
          '"

  friendsdrinks-invitation-writer-service:
    image: andyg001/friendsdrinksbackend:latest
    networks:
      - kafka-network
    volumes:
      - ./dockercompose:/app/config
    command:
      "bash -c '
          java -DlogPath=/app/ -cp /app/friendsdrinks-0.0.1.jar andrewgrant.friendsdrinks.membership.InvitationWriterService /app/config/dev.properties \
          -DlogPath=/app/
          '"

  friendsdrinks-writer-service:
    image: andyg001/friendsdrinksbackend:latest
    networks:
      - kafka-network
    volumes:
      - ./dockercompose:/app/config
    command:
      "bash -c '
          java -DlogPath=/app/ -cp /app/friendsdrinks-0.0.1.jar andrewgrant.friendsdrinks.WriterService /app/config/dev.properties \
          '"

  frontend-api:
    image: andyg001/friendsdrinksbackend:latest
    networks:
      - kafka-network
    volumes:
      - ./dockercompose:/app/config
    ports:
      - "32778:8080"
    command:
      "bash -c '
          java -DlogPath=/app/ -cp /app/friendsdrinks-0.0.1.jar andrewgrant.friendsdrinks.frontend.Main /app/config/dev.properties 8080 \
          '"

  user-service:
    image: andyg001/friendsdrinksbackend:latest
    networks:
      - kafka-network
    volumes:
      - ./dockercompose:/app/config
    command:
      "bash -c '
          java -DlogPath=/app/ -cp /app/friendsdrinks-0.0.1.jar andrewgrant.friendsdrinks.user.Service /app/config/dev.properties \
          -DlogPath=/app/
          '"

networks:
  kafka-network:
    external: true
    name: friendsdrinks_default
