---
version: '3.7'

services:
  friendsdrinks-request-service:
    image: friendsdrinks:latest
    networks:
      - kafka-network
    command:
      "bash -c '
          java -DlogPath=/app/ -cp /app/friendsdrinks-0.0.1.jar andrewgrant.friendsdrinks.RequestService /app/dev.properties \
          -DlogPath=/app/
          '"

  friendsdrinks-membership-request-service:
    image: friendsdrinks:latest
    networks:
      - kafka-network
    command:
      "bash -c '
          java -DlogPath=/app/ -cp /app/friendsdrinks-0.0.1.jar andrewgrant.friendsdrinks.membership.RequestService /app/dev.properties \
          -DlogPath=/app/
          '"

  friendsdrinks-membership-writer-service:
    image: friendsdrinks:latest
    networks:
      - kafka-network
    command:
      "bash -c '
          java -DlogPath=/app/ -cp /app/friendsdrinks-0.0.1.jar andrewgrant.friendsdrinks.membership.WriterService /app/dev.properties \
          -DlogPath=/app/
          '"

  friendsdrinks-writer-service:
    image: friendsdrinks:latest
    networks:
      - kafka-network
    command:
      "bash -c '
          java -DlogPath=/app/ -cp /app/friendsdrinks-0.0.1.jar andrewgrant.friendsdrinks.WriterService /app/dev.properties \
          '"

  frontend-api:
    image: friendsdrinks:latest
    networks:
      - kafka-network
    ports:
      - "32778:8080"
    command:
      "bash -c '
          java -DlogPath=/app/ -cp /app/friendsdrinks-0.0.1.jar andrewgrant.friendsdrinks.frontend.restapi.Main /app/dev.properties 8080 \
          '"

  user-service:
    image: friendsdrinks:latest
    networks:
      - kafka-network
    command:
      "bash -c '
          java -DlogPath=/app/ -cp /app/friendsdrinks-0.0.1.jar andrewgrant.friendsdrinks.user.Service /app/dev.properties \
          -DlogPath=/app/
          '"

networks:
  kafka-network:
    external: true
    name: friendsdrinks_default
