---
version: '3.7'

services:
  email-writer:
   image: fdimage:latest
   networks:
     - kafka-network
   command:
     "bash -c '
          java -cp /app/friendsdrinks-0.0.1.jar andrewgrant.friendsdrinks.email.WriterService /app/dev.properties
          '"

  email-create-user-validation-service:
    image: fdimage:latest
    networks:
      - kafka-network
    command:
      "bash -c '
          java -cp /app/friendsdrinks-0.0.1.jar andrewgrant.friendsdrinks.email.CreateUserValidationService /app/dev.properties
          '"
  email-delete-user-validation-service:
    image: fdimage:latest
    networks:
      - kafka-network
    command:
      "bash -c '
          java -cp /app/friendsdrinks-0.0.1.jar andrewgrant.friendsdrinks.email.DeleteUserValidationService /app/dev.properties
          '"

  fraud-validation-service:
    image: fdimage:latest
    networks:
      - kafka-network
    command:
      "bash -c '
          java -cp /app/friendsdrinks-0.0.1.jar andrewgrant.friendsdrinks.fraud.ValidationService /app/dev.properties
          '"

  user-validation-service:
    image: fdimage:latest
    networks:
      - kafka-network
    command:
      "bash -c '
          java -cp /app/friendsdrinks-0.0.1.jar andrewgrant.friendsdrinks.user.ValidationService /app/dev.properties
          '"

  create-user-validation-aggregator-service:
    image: fdimage:latest
    networks:
      - kafka-network
    command:
      "bash -c '
          java -cp /app/friendsdrinks-0.0.1.jar andrewgrant.friendsdrinks.user.CreateUserValidationAggregatorService /app/dev.properties
          '"

  delete-user-validation-aggregator-service:
    image: fdimage:latest
    networks:
      - kafka-network
    command:
      "bash -c '
          java -cp /app/friendsdrinks-0.0.1.jar andrewgrant.friendsdrinks.user.DeleteUserValidationAggregatorService /app/dev.properties
          '"

  front-end-api:
    image: fdimage:latest
    networks:
      - kafka-network
    ports:
      - "8080"
    command:
      "bash -c '
          java -cp /app/friendsdrinks-0.0.1.jar andrewgrant.friendsdrinks.frontend.restapi.Main /app/dev.properties 8080
          '"

networks:
  kafka-network:
    external: true
    name: friendsdrinks_default
