apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-reader-role
rules:
  - apiGroups: [""]
    verbs: ["get", "watch", "list"]
    resources: ["pods", "nodes"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-reader-role-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: kafka
roleRef:
  kind: ClusterRole
  name: cluster-reader-role
  apiGroup: rbac.authorization.k8s.io