apiVersion: v1
kind: Service
metadata:
  name: frontendapi-cs
  labels:
    app: frontendapi-service
spec:
  type: NodePort
  ports:
    - port: 8080
      name: client
  selector:
    app: frontendapi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendapi-deployment
  labels:
    app: frontendapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontendapi
  template:
    metadata:
      labels:
        app: frontendapi
    spec:
      containers:
        - name: frontendapi-container
          image: fdimage:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          command:
            - sh
            - -c
            - "java -cp /app/friendsdrinks-0.0.1.jar andrewgrant.friendsdrinks.frontend.restapi.Main /app/dev.properties 8080"
