apiVersion: v1
kind: Service
metadata:
  name: schema-registry-cs
  labels:
    app: schema-registry
spec:
  ports:
    - port: 8081
      name: server
  selector:
    app: schema-registry
---
apiVersion: v1
kind: Pod
metadata:
  name: schema-registry
  labels:
    app: schema-registry
spec:
  containers:
    - name: schema-registry
      image: confluentinc/cp-schema-registry:5.3.0
      env:
        - name: SCHEMA_REGISTRY_HOST_NAME
          value: "schema-registry"
        - name: SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL
          value: "zk-cs:2181"
        - name: SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL
          value: "WARN"
      ports:
        - containerPort: 8081
          name: server
