apiVersion: v1
kind: Service
metadata:
  name: zk-hs
  labels:
    app: zk
spec:
  ports:
    - port: 2888
      name: server
    - port: 3888
      name: leader-election
  clusterIP: None
  selector:
    app: zk
---
apiVersion: v1
kind: Service
metadata:
  name: zk-cs
  labels:
    app: zk
spec:
  ports:
    - port: 2181
      name: client
  selector:
    app: zk
---
apiVersion: v1
kind: Pod
metadata:
  name: zk1
  labels:
    app: zk
spec:
  hostname: zk1
  subdomain: zk-hs
  containers:
    - name: zookeeper-container
      image: confluentinc/cp-zookeeper:5.3.0
      env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
        - name: ZOOKEEPER_SERVER_ID
          value: "1"
        - name: ZOOKEEPER_SERVERS
          value: "zk1.zk-hs.default.svc.cluster.local:2888:3888;zk2.zk-hs.default.svc.cluster.local:2888:3888;zk3.zk-hs.default.svc.cluster.local:2888:3888"
      ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: server
        - containerPort: 3888
          name: leader-election

---
apiVersion: v1
kind: Pod
metadata:
  name: zk2
  labels:
    app: zk
spec:
  hostname: zk2
  subdomain: zk-hs
  containers:
    - name: zookeeper-container
      image: confluentinc/cp-zookeeper:5.3.0
      env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
        - name: ZOOKEEPER_SERVER_ID
          value: "2"
        - name: ZOOKEEPER_SERVERS
          value: "zk1.zk-hs.default.svc.cluster.local:2888:3888;zk2.zk-hs.default.svc.cluster.local:2888:3888;zk3.zk-hs.default.svc.cluster.local:2888:3888"

      ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: server
        - containerPort: 3888
          name: leader-election
---
apiVersion: v1
kind: Pod
metadata:
  name: zk3
  labels:
    app: zk
spec:
  hostname: zk3
  subdomain: zk-hs
  containers:
    - name: zookeeper-container
      image: confluentinc/cp-zookeeper:5.3.0
      env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
        - name: ZOOKEEPER_SERVER_ID
          value: "3"
        - name: ZOOKEEPER_SERVERS
          value: "zk1.zk-hs.default.svc.cluster.local:2888:3888;zk2.zk-hs.default.svc.cluster.local:2888:3888;zk3.zk-hs.default.svc.cluster.local:2888:3888"
      ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: server
        - containerPort: 3888
          name: leader-election
