apiVersion: apps/v1
kind: Deployment
metadata:
  name: friendsdrinks-membership-request-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: friendsdrinks-membership-request-service
  template:
    metadata:
      labels:
        app: friendsdrinks-membership-request-service
    spec:
      containers:
        - name: friendsdrinks-memberhip-request-service
          image: $img
          imagePullPolicy: Always
          volumeMounts:
            - name: config
              mountPath: /app/config
              readOnly: true
          livenessProbe:
            httpGet:
              path: /v1/health
              port: 8080
            initialDelaySeconds: 240
          ports:
            - containerPort: 8080
          args: ["andrewgrant.friendsdrinks.membership.RequestService", "/app/config/dev-kubernetes.properties"]
      volumes:
        - name: config
          configMap:
            name: streams-config
