version: v1.0
name: Application deploy
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
auto_cancel:
  queued:
    when: "true" # enable auto-cancel for branches, tags and pull-requests
blocks:
  - name: Create topics and deploy app config to Kubernetes
    task:
      prologue:
        commands:
          - checkout
          - cache list
          - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          - unzip awscliv2.zip
          - sudo ./aws/install
          - aws --version
      jobs:
        - name: Config deployment and job to create topics
          commands:
            - source semaphore/iamenvsetup 2>&1
            - aws eks update-kubeconfig --name EKSCluster --kubeconfig awskubeconfig
            - kubectl --kubeconfig awskubeconfig cluster-info
            - kubectl --kubeconfig awskubeconfig get nodes
            - kubectl --kubeconfig awskubeconfig apply -f kubernetes/streamsapp/10create_kafka_topics_job.yml
            - kubectl --kubeconfig awskubeconfig wait --for=condition=complete job/kafka-create-topics-job --timeout=600s
            - kubectl --kubeconfig awskubeconfig apply -f kubernetes/streamsapp/20streams_config.yml
      secrets:
        - name: iam-user-secret
      env_vars:
        - name: AWS_DEFAULT_REGION
          value: us-east-1
  - name: Deploy app to Kubernetes
    task:
      prologue:
        commands:
          - checkout
          - cache list
          - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          - unzip awscliv2.zip
          - sudo ./aws/install
          - aws --version
      jobs:
        - name: FriendsDrinks invitation writer service deployment
          commands:
            - source semaphore/iamenvsetup 2>&1
            - aws eks update-kubeconfig --name EKSCluster --kubeconfig awskubeconfig
            - kubectl --kubeconfig awskubeconfig cluster-info
            - kubectl --kubeconfig awskubeconfig get nodes
            - apply_tmp=$(mktemp)
            - ./kubernetes/streamsapp/generate_manifest.sh kubernetes/streamsapp/friendsdrinks_invitation_writer_service.yml $DOCKER_USERNAME/friendsdrinksbackend:$SEMAPHORE_WORKFLOW_ID $apply_tmp
            - cat $apply_tmp
            - kubectl --kubeconfig awskubeconfig apply -f $apply_tmp
            - kubectl --kubeconfig awskubeconfig rollout status -f $apply_tmp
            - rm -f $apply_tmp
        - name: FriendsDrinks meetup writer service deployment
          commands:
            - source semaphore/iamenvsetup 2>&1
            - aws eks update-kubeconfig --name EKSCluster --kubeconfig awskubeconfig
            - kubectl --kubeconfig awskubeconfig cluster-info
            - kubectl --kubeconfig awskubeconfig get nodes
            - apply_tmp=$(mktemp)
            - ./kubernetes/streamsapp/generate_manifest.sh kubernetes/streamsapp/friendsdrinks_meetup_writer_service.yml $DOCKER_USERNAME/friendsdrinksbackend:$SEMAPHORE_WORKFLOW_ID $apply_tmp
            - cat $apply_tmp
            - kubectl --kubeconfig awskubeconfig apply -f $apply_tmp
            - kubectl --kubeconfig awskubeconfig rollout status -f $apply_tmp
            - rm -f $apply_tmp
        - name: FriendsDrinks membership request service deployment
          commands:
            - source semaphore/iamenvsetup 2>&1
            - aws eks update-kubeconfig --name EKSCluster --kubeconfig awskubeconfig
            - kubectl --kubeconfig awskubeconfig cluster-info
            - kubectl --kubeconfig awskubeconfig get nodes
            - apply_tmp=$(mktemp)
            - ./kubernetes/streamsapp/generate_manifest.sh kubernetes/streamsapp/friendsdrinks_membership_request_service.yml $DOCKER_USERNAME/friendsdrinksbackend:$SEMAPHORE_WORKFLOW_ID $apply_tmp
            - cat $apply_tmp
            - kubectl --kubeconfig awskubeconfig apply -f $apply_tmp
            - kubectl --kubeconfig awskubeconfig rollout status -f $apply_tmp
            - rm -f $apply_tmp
        - name: FriendsDrinks membershpi writer service deployment
          commands:
            - source semaphore/iamenvsetup 2>&1
            - aws eks update-kubeconfig --name EKSCluster --kubeconfig awskubeconfig
            - kubectl --kubeconfig awskubeconfig cluster-info
            - kubectl --kubeconfig awskubeconfig get nodes
            - apply_tmp=$(mktemp)
            - ./kubernetes/streamsapp/generate_manifest.sh kubernetes/streamsapp/friendsdrinks_membership_writer_service.yml $DOCKER_USERNAME/friendsdrinksbackend:$SEMAPHORE_WORKFLOW_ID $apply_tmp
            - cat $apply_tmp
            - kubectl --kubeconfig awskubeconfig apply -f $apply_tmp
            - kubectl --kubeconfig awskubeconfig rollout status -f $apply_tmp
            - rm -f $apply_tmp
        - name: FriendsDrinks request service deployment
          commands:
            - source semaphore/iamenvsetup 2>&1
            - aws eks update-kubeconfig --name EKSCluster --kubeconfig awskubeconfig
            - kubectl --kubeconfig awskubeconfig cluster-info
            - kubectl --kubeconfig awskubeconfig get nodes
            - apply_tmp=$(mktemp)
            - ./kubernetes/streamsapp/generate_manifest.sh kubernetes/streamsapp/friendsdrinks_request_service.yml $DOCKER_USERNAME/friendsdrinksbackend:$SEMAPHORE_WORKFLOW_ID $apply_tmp
            - cat $apply_tmp
            - kubectl --kubeconfig awskubeconfig apply -f $apply_tmp
            - kubectl --kubeconfig awskubeconfig rollout status -f $apply_tmp
            - rm -f $apply_tmp
        - name: FriendsDrinks writer service deployment
          commands:
            - source semaphore/iamenvsetup 2>&1
            - aws eks update-kubeconfig --name EKSCluster --kubeconfig awskubeconfig
            - kubectl --kubeconfig awskubeconfig cluster-info
            - kubectl --kubeconfig awskubeconfig get nodes
            - apply_tmp=$(mktemp)
            - ./kubernetes/streamsapp/generate_manifest.sh kubernetes/streamsapp/friendsdrinks_writer_service.yml $DOCKER_USERNAME/friendsdrinksbackend:$SEMAPHORE_WORKFLOW_ID $apply_tmp
            - cat $apply_tmp
            - kubectl --kubeconfig awskubeconfig apply -f $apply_tmp
            - kubectl --kubeconfig awskubeconfig rollout status -f $apply_tmp
            - rm -f $apply_tmp
        - name: User service deployment
          commands:
            - source semaphore/iamenvsetup 2>&1
            - aws eks update-kubeconfig --name EKSCluster --kubeconfig awskubeconfig
            - kubectl --kubeconfig awskubeconfig cluster-info
            - kubectl --kubeconfig awskubeconfig get nodes
            - apply_tmp=$(mktemp)
            - ./kubernetes/streamsapp/generate_manifest.sh kubernetes/streamsapp/user_service.yml $DOCKER_USERNAME/friendsdrinksbackend:$SEMAPHORE_WORKFLOW_ID $apply_tmp
            - cat $apply_tmp
            - kubectl --kubeconfig awskubeconfig apply -f $apply_tmp
            - kubectl --kubeconfig awskubeconfig rollout status -f $apply_tmp
            - rm -f $apply_tmp
      secrets:
        - name: iam-user-secret
        - name: docker-hub-secret
      env_vars:
        - name: AWS_DEFAULT_REGION
          value: us-east-1